apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  sourceRef:
    kind: OCIRepository
    name: kyverno-policies
  interval: 60m
  retryInterval: 5m
  path: ./
  prune: true
  wait: true
  timeout: 2m
  patches: # enforce all policies
    - patch: |
        - op: add
          path: /spec/validationFailureAction
          value: enforce
      target:
        kind: ClusterPolicy
