apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  interval: 5m
  url: oci://ghcr.io/developer-guy/policies
  ref:
    semver: "v0.1.0"
  secretRef:
    name: ghcr-auth
